### PR TITLE
Minor changes in singly linked list example 

### PR DESCRIPTION
**Pull request by CodingAndTechnology**
Hello,
Thanks for the previous merge. Creating this PR as the linked list example needed a small change to be passed in CI. Can we please merge this as well. Thanks!

### CODE REVIEW

**Comment by jiacai2050** [comment]
Fixed in https://github.com/zigcc/zig-cookbook/pull/48

**Comment by CodingAndTechnology** [comment]
Thank you for the fix. Could you please also help on if my example of linked list be present in the zig-cookbook. Thanks again!

**Comment by jiacai2050** [comment]
Working on it, this example still need some polish, so take your time.

**Comment by jiacai2050** [comment]
It's there: https://zigcc.github.io/zig-cookbook/12-02-singly-linked-list.html

**Comment by CodingAndTechnology** [comment]
Thank you so much. Your help really helped me learn more about zig and git. Looking forward to contributing more in future.

**Pull request closed without merging**
